### ISSUE TITLE
feat: aggregate pull requests that are from the user team and those that are not

### ISSUE THREAD

**Issue by mikededo** [github-stats-22/github-stats#80]
## Details

- [ ] Create a `PullRequestAggregation` model
- [ ] Count pull requests that are from a user's team
- [ ] Count pull requests that are not from a user's team

**Comment by manerow** [comment]
About the `PullRequestAggregation` model. I think we would reduce the code duplicity and simplify the calculations about the PRs inside/outside the teams if we don't compute the pull request counts at the time of receiving data from the GitHub API. Instead of that, we should insert all the obtained `PullRequest` entities to our DB and then make specific usecases querying the DB (with custom SQL Queries) for that PRs count information. Doing this the calculations would reuse the same usecases if we fetch the information from GitHub or if we already have it and get it from our DB.

**Comment by mikededo** [comment]
So we would calculate the aggregation using sql? Should the same be done with commits?

**Comment by sdomingobasora** [comment]
> Doing this the calculations would reuse the same usecases if we fetch the information from GitHub or if we already have it and get it from our DB.

@manerow can you clarify this part? I think the use cases that obtain the data from source are different than the use cases that perform calculations. The aggregation in use cases like `AggregateCommits` and `AggregateUserReviews` is done with arbitrary `List`s, which can either obtained from API or DB. Couldn't we take the same approach here?

Personally, I would keep the same approach than the other `Aggregate` use cases. However, if we accept your approach, I would change the other aggregation use cases as well, as @mikededo pointed out regarding the commits.

**Comment by sdomingobasora** [comment]
Guys, do you mind if I take care of this issue? @mikededo @manerow

**Comment by mikededo** [comment]
Nope, now that I see it it looks more like a @undefined team issue, isn't it? I understand that it would not involve the GitHub part, rather the data obtained from the database, am I right?

**Comment by mikededo** [comment]
FYI: You have more info in #70.

**Comment by mikededo** [comment]
Exam time now 😱

**Comment by mikededo** [comment]
Closing for updates in #157, #158, #159, #160
